### ISSUE TITLE
Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by pirimoglu** [markmcdowell/NLog.Targets.ElasticSearch#139]
Newtonsoft.Json dependency can be changed with System.Text.Json

**Comment by snakefoot** [comment]
Yes but there are different side-effects:
- System.Text.Json doesn't implement reference loop protection.
- System.Text.Json doesn't render double zero as `0.0` but as `0` (Can give funny datatype-guessing issue when indexing)
- System.Text.Json doesn't render fields by default (can be forced on)
- System.Text.Json doesn't recognize the class-attributes from Newtonsoft.Json.
- System.Text.Json carries a lot of new dependencies for .NetFramework, and those can be annoying because of strong-version issues.

See also: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

**Comment by snakefoot** [comment]
Guess one could look into trying to exercise the NEST-serializer, instead of using Newtonsoft.Json

**Comment by wonea** [comment]
On the roadmap for version 8.0 of [elasticsearch-net](https://github.com/elastic/elasticsearch-net)

https://github.com/elastic/elasticsearch-net/issues/5941
