### ISSUE TITLE
Upgrade to dotnet 5

### ISSUE THREAD

**Issue by qcerasmus** [markmcdowell/NLog.Targets.ElasticSearch#145]
I have upgraded the project to dotnet5.
This did unfortunately have breaking changes so I fixed those as well.

**Comment by snakefoot** [comment]
Think the problem you see with "breadking" changes, is caused by you "upgrading" to NLog 5.0-beta.

You should stay away from NLog 5.0-beta/prerelease, since they were early attempts to support NetCore. But then Microsoft introduced NetStandard2 and then NLog 4.5 could be made. See also "What happend to NLog 5?" https://nlog-project.org/2017/12/20/nlog-4-5-is-near.html

https://www.nuget.org/packages/NLog.Targets.ElasticSearch ver. 7.5.0 works just fine with Net50.
