### ISSUE TITLE
Include all MDLC properties to Elasticsearch

### ISSUE THREAD

**Issue by pardahlman** [markmcdowell/NLog.Targets.ElasticSearch#74]
My apologies for this very basic question, but I've read through the source code and looked in the documentation without finding what I'm looking for. I haven't been able to wrap my head around all the NLog concepts of properties and properties saved in different "contexts".

I use the `MappedDiagnosticsLogicalContext` to set context data, which I want to include in the document payload sent to Elasticsearch. I have configured `IncludeAllProperties` to `true`, but it does not include the mdlc properties.

Any ideas on how to configure the elasticsearch target so that all available properties in the `MappedDiagnosticsLogicalContext`?

**Comment by snakefoot** [comment]
Before NLog never really used `MappedDiagnosticsLogicalContext` (or `MappedDiagnosticsContext`) for anything but a single CorrelationId or SessionId (Ex `${mdlc:item}`) . This changed with structured logging where Serilog and Microsoft Extension Logging made heavy use of scope variables.

Many NLog Targets doesn't have support for capture of the entire MDLC-context. Also because it is difficult because you need cache them when in async-mode where target-write happens on another thread than the logging-thread.

I have tried to promote a new NLog Target-class called NLog-TargetWithContext, that makes it easier to correctly handle MDLC-context so it also works in async mode. But because NLog target are implemented in peoples free time, then the transition is slow.

One possible workaround for this target could be:

- Make your custom layoutrenderer that renders the entire MDLC as a JSON-string
- Setup a Field in this target with the LayoutType = typeof(object) and Layout = `${yourlayoutrenderer}`

**Comment by pardahlman** [comment]
@snakefoot thanks - again! I'll look into writing my own rendered 👍

**Comment by aheubusch** [comment]
I use something like this (don't have access to my real config, this might contain typos).
```xml
<target xsi:type="ElasticSearch">
  <field name="mdlc" layoutType="System.Object">
    <layout xsi:type="JsonLayout" includeMdlc="true" />
  </field>
</target>
```
https://github.com/nlog/NLog/wiki/JsonLayout

**Comment by snakefoot** [comment]
@aheubusch Yes that will work just fint. Think I will create a PR to reduce allocation for that scenario.
